repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Última versión
    hooks:
      - id: trailing-whitespace  # Elimina espacios en blanco finales
      - id: end-of-file-fixer     # Asegura que los archivos terminen con una línea en blanco
      - id: check-yaml            # Verifica la validez de archivos YAML
